# Generated by Django 4.1 on 2022-09-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='', upload_to='movie_pics'),
            preserve_default=False,
        ),
    ]
